### ISSUE TITLE
No output written due to: X Error of failed request:  BadLength (poly request too large or internal Xlib length error)

### ISSUE THREAD

**Issue by Wikinaut** [blackstream-x/pyxelate#47]
```
./autoselect.py 1.mp4
INFO    ║ __do_load_video → '1.mp4' has audio: True
INFO    ║ __do_load_video → Created tempdir '/tmp/tmpvh4fs9e7'
INFO    ║ action_preview → Created tempdir '/tmp/tmpfe982s1j'
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  35713
  Current serial number in output stream:  35715
Traceback (most recent call last):
  File "./autoselect.py", line 228, in <module>
    sys.exit(main(__get_arguments()))
  File "./autoselect.py", line 221, in main
    return start_matching_script(selected_file)
  File "./autoselect.py", line 147, in start_matching_script
    return subprocess.run(command, check=True).returncode
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/benutzer/src/pyxelate/pixelate_video.py', '1.mp4']' returned non-zero exit status 1.
```

**Comment by blackstream-x** [comment]
I think I hav do add more debugging output, to determine where exactly the error occurs.

**Comment by Wikinaut** [comment]
debug output: https://dpaste.com/E33UH2TSR.txt

**Comment by blackstream-x** [comment]
Probably caused by the now-removed preview buttons
